export const candidatesFull = [
    {
        id: 1,
        name: 'Сидоренко Валентин',
        tags: ['#Прикольный'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Пекарь электромонтер',
        vacancy: 'Менеджер по продажам',
        stage: 'Новый',
        location: 'Москва',
        phone: '+7-999-233-0978',
        email: 'andryalexeev112@gmail.com',
        skype: 'ale129x.skype',
        telegram: 'lexso21238s'
    },
    {
        id: 2,
        name: 'Сидоренко Валентин',
        tags: ['#подходящий', '#IT'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Пекарь электромонтер',
        vacancy: 'Менеджер по продажам',
        stage: 'Новый',
        location: 'Москва',
        phone: '+7-999-233-0978',
        email: 'andryalexeev112@gmail.com',
        skype: 'ale129x.skype',
        telegram: 'lexso21238s'
    },
    {
        id: 3,
        name: 'Сидоренко Валентин3',
        tags: ['#подходящий', '#IT'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Пекарь электромонтер',
        vacancy: 'Менеджер по продажам',
        stage: 'Новый',
        location: 'Москва',
        phone: '+7-999-233-0978',
        email: 'andryalexeev112@gmail.com',
        skype: 'ale129x.skype',
        telegram: 'lexso21238s'
    },
    {
        id: 4,
        name: 'Сидоренко Валентин',
        tags: ['#подходящий', '#IT'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Пекарь электромонтер',
        vacancy: 'Менеджер по продажам',
        stage: 'Новый',
        location: 'Москва',
        phone: '+7-999-233-0978',
        email: 'andryalexeev112@gmail.com',
        skype: 'ale129x.skype',
        telegram: 'lexso21238s'
    },
    {
        id: 5,
        name: 'Сидоренко Валентин',
        tags: ['#подходящий', '#IT'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Пекарь электромонтер',
        vacancy: 'Менеджер по продажам',
        stage: 'Новый',
        location: 'Москва',
        phone: '+7-999-233-0978',
        email: 'andryalexeev112@gmail.com',
        skype: 'ale129x.skype',
        telegram: 'lexso21238s'
    },
    {
        id: 6,
        name: 'Сидоренко Валентин',
        tags: ['#подходящий', '#IT'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Пекарь электромонтер',
        vacancy: 'Менеджер по продажам',
        stage: 'Новый',
        location: 'Москва',
        phone: '+7-999-233-0978',
        email: 'andryalexeev112@gmail.com',
        skype: 'ale129x.skype',
        telegram: 'lexso21238s'
    },
    {
        id: 7,
        name: 'Сидоренко Валентин',
        tags: ['#подходящий', '#IT'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Пекарь электромонтер',
        vacancy: 'Менеджер по продажам',
        stage: 'Новый',
        location: 'Москва',
        phone: '+7-999-233-0978',
        email: 'andryalexeev112@gmail.com',
        skype: 'ale129x.skype',
        telegram: 'lexso21238s'
    },
    {
        id: 8,
        name: 'Сидоренко Валентин',
        tags: ['#подходящий', '#IT'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Пекарь электромонтер',
        vacancy: 'Менеджер по продажам',
        stage: 'Новый',
        location: 'Москва',
        phone: '+7-999-233-0978',
        email: 'andryalexeev112@gmail.com',
        skype: 'ale129x.skype',
        telegram: 'lexso21238s'
    },
    {
        id: 9,
        name: 'Сидоренко Валентин',
        tags: ['#подходящий', '#IT'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Пекарь электромонтер',
        vacancy: 'Менеджер по продажам',
        stage: 'Новый',
        location: 'Москва',
        phone: '+7-999-233-0978',
        email: 'andryalexeev112@gmail.com',
        skype: 'ale129x.skype',
        telegram: 'lexso21238s'
    },
    {
        id: 10,
        name: 'Сидоренко Валентин',
        tags: ['#подходящий', '#IT'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Пекарь электромонтер',
        vacancy: 'Менеджер по продажам',
        stage: 'Новый',
        location: 'Москва',
        phone: '+7-999-233-0978',
        email: 'andryalexeev112@gmail.com',
        skype: 'ale129x.skype',
        telegram: 'lexso21238s'
    },
    {
        id: 11,
        name: 'Сидоренко Валентин',
        tags: ['#подходящий', '#IT'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Пекарь электромонтер',
        vacancy: 'Менеджер по продажам',
        stage: 'Новый',
        location: 'Москва',
        phone: '+7-999-233-0978',
        email: 'andryalexeev112@gmail.com',
        skype: 'ale129x.skype',
        telegram: 'lexso21238s'
    }
]