export const candidatesFull = [
    {
        id: 1,
        surname: 'Сидоренко',
        firstName: 'Валентин',
        patronymic: 'Петрович',
        tags: ['#Прикольный'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Пекарь электромонтер',
        vacancy: 'Менеджер по продажам',
        stage: 'Новый',
        location: 'Москва',
        locationFull: 'г. Санкт-Петербург, ул. Шапранова 19',
        phone: '+7-999-233-0978',
        email: 'andryalexeev112@gmail.com',
        skype: 'ale129x.skype',
        telegram: 'lexso21238s',
        quickInfo: 'Я опытный профессионал и лидер. Увлеченный своей работой, я ориентирован на результат. Чем сложнее задача, тем более вовлеченным я становлюсь. Я с удовольствием придумываю большие идеи, и мне нравится работать с командами по всему миру. У меня уникальная способность ориентироваться в нескольких проектах и сложных задачах.',
        education: 'Московский государственный университет (2005-2009)',
        educationLevel: 'Начальное',
        skills: ['Продажи', 'Прямые продажи', 'Прямые продажи', 'Маркетинг продукция', 'программное обеспечение CRM', 'Исследования'],
        attachedFiles: [
            { name: 'Алексей Иванов', path: '/files/Алексей Иванов.pdf', type: 'pdf' },
            { name: 'Сопроводительное письмо', path: '/files/Сопроводительное письмо.txt', type: 'txt' }
        ],
        links: [
            'https://linkedin.com/in/valentin-sidorenko',
            'https://github.com/valentin-s'
        ],
        header: 'Привет, это заголовок',
        experience: '5 лет',
        photo: '/files/photo.png',
        resumeDownload: '/files/resume.pdf',
        coverLetter: '/files/paper.doc'
    },
    {
        id: 2,
        surname: 'Иванов',
        firstName: 'Алексей',
        patronymic: 'Сергеевич',
        tags: ['#IT', '#разработчик'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Frontend-разработчик',
        vacancy: 'Веб-разработчик',
        stage: 'Собеседование',
        location: 'Санкт-Петербург',
        locationFull: 'г. Санкт-Петербург, ул. Шапранова 19',
        phone: '+7-911-456-7890',
        email: 'alex.ivanov@ya.ru',
        skype: 'alex_dev',
        telegram: 'alexivan',
        quickInfo: 'Я опытный профессионал и лидер. Увлеченный своей работой, я ориентирован на результат. Чем сложнее задача, тем более вовлеченным я становлюсь. Я с удовольствием придумываю большие идеи, и мне нравится работать с командами по всему миру. У меня уникальная способность ориентироваться в нескольких проектах и сложных задачах.',
        education: 'Московский государственный университет (2005-2009)',
        educationLevel: 'Начальное',
        skills: [
            'JavaScript',
            'Vue.js',
            'React'
        ],
        attachedFiles: [
            { name: 'Сопроводительное письмо', path: '/files/Сопроводительное письмо.txt', type: 'txt' }
        ],
        links: [
            'https://github.com/alexivanov',
            'https://portfolio.alexivanov.dev'
        ],
        header: 'Привет, это заголовок',
        experience: '5 лет',
        photo: '/files/photo2.jpg',
        resumeDownload: '/files/resume.pdf',
        coverLetter: '/files/paper.doc'
    },
    {
        id: 3,
        surname: 'Петрова',
        firstName: 'Ольга',
        patronymic: '', // Отчество отсутствует
        tags: ['#маркетинг'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Маркетолог',
        vacancy: 'SMM-менеджер',
        stage: 'Тестовое задание',
        location: 'Екатеринбург',
        locationFull: 'г. Санкт-Петербург, ул. Шапранова 19',
        phone: '+7-922-123-4567',
        email: 'olga.petrova@mail.ru',
        skype: 'olga_marketing',
        telegram: 'olgapetrova',
        quickInfo: 'Я опытный профессионал и лидер. Увлеченный своей работой, я ориентирован на результат. Чем сложнее задача, тем более вовлеченным я становлюсь. Я с удовольствием придумываю большие идеи, и мне нравится работать с командами по всему миру. У меня уникальная способность ориентироваться в нескольких проектах и сложных задачах.',
        education: 'Московский государственный университет (2005-2009)',
        educationLevel: 'Начальное',
        skills: [],
        attachedFiles: [
            { name: 'Алексей Иванов', path: '/files/Алексей Иванов.pdf', type: 'pdf' }
        ],
        links: [],
        header: 'Привет, это заголовок',
        experience: '5 лет',
        photo: '/files/photo3.jpg',
        resumeDownload: '/files/resume.pdf',
        coverLetter: '/files/paper.doc'
    },
    {
        id: 4,
        surname: 'Козлов',
        firstName: 'Дмитрий',
        patronymic: 'Александрович',
        tags: ['#продажи', '#опыт'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Менеджер по продажам',
        vacancy: 'Руководитель отдела продаж',
        stage: 'Финал',
        location: 'Новосибирск',
        locationFull: 'г. Санкт-Петербург, ул. Шапранова 19',
        phone: '+7-913-987-6543',
        email: 'dmitry.kozlov@gmail.com',
        skype: 'dkozlov_sales',
        telegram: 'dmitry_k',
        quickInfo: 'Я опытный профессионал и лидер. Увлеченный своей работой, я ориентирован на результат. Чем сложнее задача, тем более вовлеченным я становлюсь. Я с удовольствием придумываю большие идеи, и мне нравится работать с командами по всему миру. У меня уникальная способность ориентироваться в нескольких проектах и сложных задачах.',
        education: 'Московский государственный университет (2005-2009)',
        educationLevel: 'Начальное',
        attachedFiles: [],
        skills: [
            'Переговоры',
            'Управление продажами'
        ],
        links: [
            'https://linkedin.com/in/dmitry-kozlov'
        ],
        header: 'Привет, это заголовок',
        experience: '5 лет',
        photo: '/files/photo.png',
        resumeDownload: '/files/resume.pdf',
        coverLetter: '/files/paper.doc'
    },
    {
        id: 5,
        surname: 'Смирнова',
        firstName: 'Екатерина',
        patronymic: 'Владимировна',
        tags: ['#дизайн', '#креатив'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'UI/UX дизайнер',
        vacancy: 'Графический дизайнер',
        stage: 'Новый',
        location: 'Казань',
        locationFull: 'г. Санкт-Петербург, ул. Шапранова 19',
        phone: '+7-917-555-1234',
        email: 'katya.smirnova@outlook.com',
        skype: 'katyadesign',
        telegram: 'katyasmirn',
        quickInfo: 'Я опытный профессионал и лидер. Увлеченный своей работой, я ориентирован на результат. Чем сложнее задача, тем более вовлеченным я становлюсь. Я с удовольствием придумываю большие идеи, и мне нравится работать с командами по всему миру. У меня уникальная способность ориентироваться в нескольких проектах и сложных задачах.',
        education: 'Московский государственный университет (2005-2009)',
        educationLevel: 'Начальное',
        skills: [
            'Figma',
            'Adobe Photoshop',
            'UI/UX'
        ],
        attachedFiles: [
            { name: 'Диплом', path: '/files/Диплом.pdf', type: 'pdf' },
            { name: 'Сопроводительное письмо', path: '/files/Сопроводительное письмо.txt', type: 'txt' }
        ],
        links: [
            'https://behance.net/katyasmirnova'
        ],
        header: 'Привет, это заголовок',
        experience: '5 лет',
        photo: '/files/photo.png',
        resumeDownload: '/files/resume.pdf',
        coverLetter: '/files/paper.doc'
    },
    {
        id: 6,
        surname: 'Морозов',
        firstName: 'Сергей',
        patronymic: 'Иванович',
        tags: ['#аналитика', '#данные'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Аналитик данных',
        vacancy: 'Data Scientist',
        stage: 'Собеседование',
        location: 'Ростов-на-Дону',
        locationFull: 'г. Санкт-Петербург, ул. Шапранова 19',
        phone: '+7-928-777-4321',
        email: 'sergey.morozov@gmail.com',
        skype: 'sergmoroz',
        telegram: 'sergey_m',
        quickInfo: 'Я опытный профессионал и лидер. Увлеченный своей работой, я ориентирован на результат. Чем сложнее задача, тем более вовлеченным я становлюсь. Я с удовольствием придумываю большие идеи, и мне нравится работать с командами по всему миру. У меня уникальная способность ориентироваться в нескольких проектах и сложных задачах.',
        education: 'Московский государственный университет (2005-2009)',
        educationLevel: 'Начальное',
        skills: [
            'Python',
            'SQL',
            'Tableau'
        ],
        attachedFiles: [
            { name: 'Алексей Иванов', path: '/files/Алексей Иванов.pdf', type: 'pdf' }
        ],
        links: [
            'https://kaggle.com/sergeymorozov'
        ],
        header: 'Привет, это заголовок',
        experience: '5 лет',
        photo: '/files/photo.png',
        resumeDownload: '/files/resume.pdf',
        coverLetter: '/files/paper.doc'
    },
    {
        id: 7,
        surname: 'Лебедева',
        firstName: 'Анна',
        patronymic: '', // Отчество отсутствует
        tags: ['#HR', '#подбор'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'HR-менеджер',
        vacancy: 'Рекрутер',
        stage: 'Новый',
        location: 'Самара',
        locationFull: 'г. Санкт-Петербург, ул. Шапранова 19',
        phone: '+7-927-654-3210',
        email: 'anna.lebedeva@ya.ru',
        skype: 'anna_hr',
        telegram: 'annalebedeva',
        quickInfo: 'Я опытный профессионал и лидер. Увлеченный своей работой, я ориентирован на результат. Чем сложнее задача, тем более вовлеченным я становлюсь. Я с удовольствием придумываю большие идеи, и мне нравится работать с командами по всему миру. У меня уникальная способность ориентироваться в нескольких проектах и сложных задачах.',
        education: 'Московский государственный университет (2005-2009)',
        educationLevel: 'Начальное',
        skills: [],
        attachedFiles: [],
        links: [],
        header: 'Привет, это заголовок',
        experience: '5 лет',
        photo: '/files/photo.png',
        resumeDownload: '/files/resume.pdf',
        coverLetter: '/files/paper.doc'
    },
    {
        id: 8,
        surname: 'Васильев',
        firstName: 'Игорь',
        patronymic: 'Николаевич',
        tags: ['#логистика'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Логист',
        vacancy: 'Менеджер по логистике',
        stage: 'Тестовое задание',
        location: 'Челябинск',
        locationFull: 'г. Санкт-Петербург, ул. Шапранова 19',
        phone: '+7-951-888-9990',
        email: 'igor.vasilyev@mail.ru',
        skype: 'igor_logist',
        telegram: 'igorvas',
        quickInfo: 'Я опытный профессионал и лидер. Увлеченный своей работой, я ориентирован на результат. Чем сложнее задача, тем более вовлеченным я становлюсь. Я с удовольствием придумываю большие идеи, и мне нравится работать с командами по всему миру. У меня уникальная способность ориентироваться в нескольких проектах и сложных задачах.',
        education: 'Московский государственный университет (2005-2009)',
        educationLevel: 'Начальное',
        skills: [
            'Планирование маршрутов',
            'Управление складом'
        ],
        attachedFiles: [
            { name: 'Сопроводительное письмо', path: '/files/Сопроводительное письмо.txt', type: 'txt' }
        ],
        links: [
            'https://linkedin.com/in/igor-vasilyev'
        ],
        header: 'Привет, это заголовок',
        experience: '5 лет',
        photo: '/files/photo.png',
        resumeDownload: '/files/resume.pdf',
        coverLetter: '/files/paper.doc'
    },
    {
        id: 9,
        surname: 'Кузнецова',
        firstName: 'Мария',
        patronymic: 'Алексеевна',
        tags: ['#финансы', '#бухгалтерия'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Бухгалтер',
        vacancy: 'Финансовый аналитик',
        stage: 'Финал',
        location: 'Краснодар',
        locationFull: 'г. Санкт-Петербург, ул. Шапранова 19',
        phone: '+7-918-333-2211',
        email: 'maria.kuznetsova@gmail.com',
        skype: 'maria_finance',
        telegram: 'mariakuz',
        quickInfo: 'Я опытный профессионал и лидер. Увлеченный своей работой, я ориентирован на результат. Чем сложнее задача, тем более вовлеченным я становлюсь. Я с удовольствием придумываю большие идеи, и мне нравится работать с командами по всему миру. У меня уникальная способность ориентироваться в нескольких проектах и сложных задачах.',
        education: 'Московский государственный университет (2005-2009)',
        educationLevel: 'Начальное',
        skills: [
            '1С',
            'Excel',
            'Финансовый анализ'
        ],
        attachedFiles: [
            { name: 'Диплом', path: '/files/Диплом.pdf', type: 'pdf' },
        ],
        links: [],
        header: 'Привет, это заголовок',
        experience: '5 лет',
        photo: '/files/photo.png',
        resumeDownload: '/files/resume.pdf',
        coverLetter: '/files/paper.doc'
    },
    {
        id: 10,
        surname: 'Тимофеев',
        firstName: 'Павел',
        patronymic: 'Викторович',
        tags: ['#управление', '#лидер'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Руководитель проектов',
        vacancy: 'Продакт-менеджер',
        stage: 'Собеседование',
        location: 'Воронеж',
        locationFull: 'г. Санкт-Петербург, ул. Шапранова 19',
        phone: '+7-920-444-5566',
        email: 'pavel.timofeev@outlook.com',
        skype: 'pavel_pm',
        telegram: 'paveltim',
        quickInfo: 'Я опытный профессионал и лидер. Увлеченный своей работой, я ориентирован на результат. Чем сложнее задача, тем более вовлеченным я становлюсь. Я с удовольствием придумываю большие идеи, и мне нравится работать с командами по всему миру. У меня уникальная способность ориентироваться в нескольких проектах и сложных задачах.',
        education: 'Московский государственный университет (2005-2009)',
        educationLevel: 'Начальное',
        skills: [
            'Scrum',
            'Agile',
            'Управление командой'
        ],
        attachedFiles: [
            { name: 'Алексей Иванов', path: '/files/Алексей Иванов.pdf', type: 'pdf' },
            { name: 'Сопроводительное письмо', path: '/files/Сопроводительное письмо.txt', type: 'txt' }
        ],
        links: [
            'https://linkedin.com/in/pavel-timofeev',
            'https://t.me/paveltimofeev'
        ],
        header: 'Привет, это заголовок',
        experience: '5 лет',
        photo: '/files/photo.png',
        resumeDownload: '/files/resume.pdf',
        coverLetter: '/files/paper.doc'
    },
    {
        id: 11,
        surname: 'Зайцева',
        firstName: 'Юлия',
        patronymic: '', // Отчество отсутствует
        tags: ['#поддержка', '#клиенты'],
        icon: "hh20",
        isPng: false,
        imagePath: "",
        resume: 'Специалист поддержки',
        vacancy: 'Менеджер по работе с клиентами',
        stage: 'Новый',
        location: 'Уфа',
        locationFull: 'г. Санкт-Петербург, ул. Шапранова 19',
        phone: '+7-937-777-8899',
        email: 'yulia.zaytseva@ya.ru',
        skype: 'yulia_support',
        telegram: 'yuliazay',
        quickInfo: 'Я опытный профессионал и лидер. Увлеченный своей работой, я ориентирован на результат. Чем сложнее задача, тем более вовлеченным я становлюсь. Я с удовольствием придумываю большие идеи, и мне нравится работать с командами по всему миру. У меня уникальная способность ориентироваться в нескольких проектах и сложных задачах.',
        education: 'Московский государственный университет (2005-2009)',
        educationLevel: 'Начальное',
        skills: [
            'Работа с клиентами',
            'CRM'
        ],
        attachedFiles: [],
        links: [
            'https://support.example.com/yulia'
        ],
        header: 'Привет, это заголовок',
        experience: '5 лет',
        photo: '/files/photo.png',
        resumeDownload: '/files/resume.pdf',
        coverLetter: '/files/paper.doc'
    }
];